version: "3.7"

services:
  nodered:
    build: ./nodered
    networks: [ "nodered" ]
    ports:
      - "1880:1880"
    volumes:
      - type: bind
        source: ./
        target: /node-red-contrib-openhab3
      - type: volume
        source: nodered-data
        target: /data

  openhab2:
    image: openhab/openhab:2.5.12-debian
    networks: [ "nodered" ]
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./test/openhab/conf/items
        target: /openhab/conf/items
      - type: volume
        source: openhab2-userdata
        target: /openhab/userdata
      - type: volume
        source: openhab2-addons
        target: /openhab/addons
    environment:
      - CRYPTO_POLICY=unlimited
      - USER_ID=9001
      - GROUP_ID=9001
      # https://community.openhab.org/t/log4shell-security-vulnerability-endangers-systems-worldwide/130314/2
      - "JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true"

  openhab3:
    build: openhab3/
    networks: [ "nodered" ]
    ports:
      - "8081:8080"
    volumes:
      - type: bind
        source: ./test/openhab/conf/items
        target: /openhab/conf/items
      - type: bind
        source: ./test/openhab/conf/persistence
        target: /openhab/conf/persistence
      - type: bind
        source: ./test/openhab/conf/services
        target: /openhab/conf/services
      - type: volume
        source: openhab3-userdata
        target: /openhab/userdata
      - type: volume
        source: openhab3-addons
        target: /openhab/addons
    environment:
      - CRYPTO_POLICY=unlimited
      - USER_ID=9001
      - GROUP_ID=9001

  openhab3-oauth2:
    build: openhab3/
    networks: [ "nodered" ]
    ports:
      - "8082:8080"
    volumes:
      - type: bind
        source: ./test/openhab/conf/items
        target: /openhab/conf/items
      - type: volume
        source: openhab3-oauth2-userdata
        target: /openhab/userdata
      - type: volume
        source: openhab3-oauth2-addons
        target: /openhab/addons
    environment:
      - CRYPTO_POLICY=unlimited
      - USER_ID=9001
      - GROUP_ID=9001

volumes:
  nodered-data:
  openhab2-addons:
  openhab2-userdata:
  openhab3-addons:
  openhab3-userdata:
  openhab3-oauth2-addons:
  openhab3-oauth2-userdata:

networks:
  nodered:
