version: "3.9"

services:
  nodered:
    build: ./nodered
    networks: [ "nodered" ]
    ports:
      - "1880:1880"
    volumes:
      - type: bind
        source: ./
        target: /node-red-contrib-openhab3
      - type: volume
        source: nodered-data
        target: /data

  openhab32:
    build: openhab3.2/
    networks: [ "nodered" ]
    ports:
      - "8081:8080"
    volumes:
      - type: bind
        source: ./test/openhab/conf/items
        target: /openhab/conf/items
      - type: bind
        source: ./test/openhab/conf/persistence
        target: /openhab/conf/persistence
      - type: bind
        source: ./test/openhab/conf/services
        target: /openhab/conf/services
      - type: volume
        source: openhab32-userdata
        target: /openhab/userdata
      - type: volume
        source: openhab32-addons
        target: /openhab/addons
    environment:
      - CRYPTO_POLICY=unlimited
      - USER_ID=9001
      - GROUP_ID=9001

  openhab33-oauth2:
    build: openhab3.3/
    networks: [ "nodered" ]
    ports:
      - "8082:8080"
    volumes:
      - type: bind
        source: ./test/openhab/conf/items
        target: /openhab/conf/items
      - type: volume
        source: openhab33-oauth2-userdata
        target: /openhab/userdata
      - type: volume
        source: openhab33-oauth2-addons
        target: /openhab/addons
    environment:
      - CRYPTO_POLICY=unlimited
      - USER_ID=9001
      - GROUP_ID=9001

  openhab33:
    build: openhab3.3/
    networks: [ "nodered" ]
    ports:
      - "8083:8080"
    volumes:
      - type: bind
        source: ./test/openhab/conf/items
        target: /openhab/conf/items
      - type: bind
        source: ./test/openhab/conf/persistence
        target: /openhab/conf/persistence
      - type: bind
        source: ./test/openhab/conf/services
        target: /openhab/conf/services
      - type: volume
        source: openhab33-userdata
        target: /openhab/userdata
      - type: volume
        source: openhab33-addons
        target: /openhab/addons
    environment:
      - CRYPTO_POLICY=unlimited
      - USER_ID=9001
      - GROUP_ID=9001

volumes:
  nodered-data:
  openhab32-addons:
  openhab32-userdata:
  openhab33-addons:
  openhab33-userdata:
  openhab33-oauth2-addons:
  openhab33-oauth2-userdata:

networks:
  nodered:
